# Generated by Django 4.2.7 on 2023-12-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=100)),
                ('no_of_people', models.IntegerField()),
                ('image', models.ImageField(upload_to='static/photos/')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
