# Generated by Django 4.2.7 on 2023-12-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
