# Generated by Django 4.2.7 on 2023-12-03 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booktable', '0002_alter_booktable_image'),
        ('managebookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managebookings',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='managebookings',
            name='is_confirm',
        ),
        migrations.RemoveField(
            model_name='managebookings',
            name='user_id',
        ),
        migrations.AddField(
            model_name='managebookings',
            name='booking_confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='managebookings',
            name='booking_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managebookings',
            name='table_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booktable.booktable'),
        ),
        migrations.AddField(
            model_name='managebookings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
