# Generated by Django 4.2.7 on 2023-12-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managebookings', '0002_remove_managebookings_booking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managebookings',
            name='table_id',
        ),
        migrations.RemoveField(
            model_name='managebookings',
            name='user',
        ),
    ]
