# Generated by Django 4.2.7 on 2023-12-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managebookings', '0003_remove_managebookings_table_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Managebookings',
        ),
    ]
