# Generated by Django 4.2.7 on 2023-12-03 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booktable', '0002_alter_booktable_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managebookings', '0004_delete_managebookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managebookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_cost', models.IntegerField()),
                ('booking_confirm', models.BooleanField(default=False)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktable.booktable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
