# Generated by Django 4.2.7 on 2023-12-03 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managebookings', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managebookings',
            name='booking_cost',
        ),
    ]
